{
 "title": "Execution Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ataka_database", "query": "grafana-postgresql-datasource" },
   { "name": "ctf_start", "query": "1970-00-00T00:00:00.000Z" },
   { "name": "tick_time", "query": "1m" },
   {
    "name": "target",
    "query": "SELECT targets.ip\nFROM targets\nGROUP BY targets.ip\nORDER BY inet(targets.ip)"
   },
   {
    "name": "service",
    "query": "SELECT targets.service FROM targets GROUP BY targets.service ORDER BY targets.service;"
   },
   {
    "name": "exploit_history",
    "query": "SELECT exploit_histories.id FROM exploit_histories WHERE exploit_histories.service IN ($service);"
   },
   {
    "name": "exploit",
    "query": "SELECT exploits.id\nFROM exploits\nWHERE exploits.exploit_history_id IN ( $exploit_history )"
   },
   {
    "name": "job",
    "query": "SELECT jobs.id\nFROM jobs\nWHERE jobs.exploit_id IN ( $exploit )"
   },
   {
    "name": "execution",
    "query": "SELECT\n  executions.id\nFROM\n  executions\n  JOIN jobs ON jobs.id = executions.job_id\n  JOIN targets ON targets.id = executions.target_id\nWHERE jobs.id IN ( ${job_nullable:csv} )\n  AND targets.ip IN ( $target )"
   },
   {
    "name": "execution_nullable",
    "query": "SELECT CASE WHEN '${execution:csv}' IN ('', ' ') THEN '-1' ELSE '${execution:csv}' END"
   },
   {
    "name": "job_nullable",
    "query": "SELECT CASE WHEN '${job:csv}' IN ('', ' ') THEN '-1' ELSE '${job:csv}' END"
   }
  ]
 },
 "panels": [
  {
   "title": "Select execution",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  executions.timestamp AS \"Execution timestamp\",\n  executions.id AS \"Execution id\",\n  executions.job_id AS \"Job id\",\n  targets.ip AS \"Target IP\",\n  COUNT(flags_filtered.id) AS \"OK Flags\"\nFROM\n  executions\n  JOIN targets ON targets.id = executions.target_id\n  LEFT JOIN (\n    SELECT\n      flags.id, flags.execution_id\n    FROM\n      flags\n    WHERE\n      flags.status = 'OK'\n    ) AS flags_filtered ON flags_filtered.execution_id = executions.id\nWHERE\n  executions.id IN ( ${execution_nullable:csv} )\n  AND targets.ip IN ( ${target:sqlstring} )\nGROUP BY\n  executions.id,\n  targets.id\nORDER BY\n  executions.timestamp DESC,\n  inet(targets.ip)"
    }
   ]
  },
  {
   "title": "Flags",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  flags.flag,\n  flags.status,\n  flags.stdout\nFROM\n  executions\n  JOIN flags ON flags.execution_id = executions.id\nWHERE executions.id IN ( ${execution_nullable:csv} )\nORDER BY flags.timestamp ASC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Flag status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  flags.status,\n  COUNT(flags.flag)\nFROM\n  executions\n  JOIN flags ON flags.execution_id = executions.id\nWHERE executions.id IN ( ${execution_nullable:csv} )\nGROUP BY flags.status\n;"
    }
   ]
  },
  {
   "title": "Viewing Tick",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(EXTRACT(EPOCH FROM ((SELECT timestamp FROM executions WHERE id IN ( ${execution_nullable:csv} ) ORDER BY id DESC LIMIT 1) - TIMESTAMP '$ctf_start')) AS INTEGER) / CAST(EXTRACT(EPOCH FROM INTERVAL '$tick_time') AS INTEGER) as current_tick;"
    }
   ]
  },
  {
   "title": "Extra",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  targets.extra\nFROM\n  executions\n  JOIN targets ON targets.id = executions.target_id\nWHERE\n  executions.id IN ( ${execution_nullable:csv} )\nORDER BY\n  executions.id DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Stdout",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  executions.stdout\nFROM\n  executions\nWHERE\n  executions.id IN ( ${execution_nullable:csv} )\nORDER BY\n  executions.id DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Stderr",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  executions.stderr\nFROM\n  executions\nWHERE\n  executions.id IN ( ${execution_nullable:csv} )\nORDER BY\n  executions.id DESC\nLIMIT 10\n"
    }
   ]
  }
 ]
}