{
 "title": "ATAKA Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "services",
    "query": "SELECT targets.service FROM targets GROUP BY targets.service ORDER BY targets.service;"
   },
   { "name": "tick_time", "query": "1m" },
   { "name": "ctf_start", "query": "1970-00-00T00:00:00.000Z" },
   { "name": "ataka_database", "query": "grafana-postgresql-datasource" },
   {
    "name": "show_status",
    "label": "Show status",
    "query": "VALUES\n('OK'),\n('QUEUED'),\n('PENDING'),\n('RESUBMIT'),\n('ERROR'),\n('DUPLICATE'),\n('DUPLICATE_NOT_SUBMITTED'),\n('NOP'),\n('OWNFLAG'),\n('INVALID'),\n('INACTIVE'),\n('UNKNOWN')"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flags overall",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(COUNT(flags.id), 0) AS \"OK\" ,\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start')\nFROM\n  executions\n  INNER JOIN jobs ON jobs.id = executions.job_id\n  INNER JOIN exploits ON jobs.exploit_id = exploits.id\n  LEFT JOIN flags ON flags.execution_id = executions.id\nWHERE\n  flags.status = 'OK'\n  AND $__timeFilter(executions.timestamp)\nGROUP BY\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start')\nORDER BY\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start')\n;"
    }
   ]
  },
  {
   "title": "Command Syntax",
   "type": "text",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "```sh\natk reload\n\natk exploit create [OPTIONS] HISTORY_ID SERVICE\natk exploit template [OPTIONS] TEMPLATE PATH\n    --overwrite\natk exploit upload [OPTIONS] HISTORY_ID AUTHOR CONTEXT\natk exploit download [OPTIONS] EXPLOIT_ID PATH\natk exploit activate [OPTIONS] EXPLOIT_ID\natk exploit deactivate [OPTIONS] EXPLOIT_ID\natk exploit logs [OPTIONS] EXPLOIT_ID_OR_HISTORY_ID ...\natk exploit ls [OPTIONS] [HISTORY_IDS] ...\natk exploit runlocal [OPTIONS] PATH SERVICE\n    --target TARGET\n    --no-target TARGET\n    --all-targets\n    --ignore-exclusions\n    --timeout SECONDS\n    --jobs PARALLEL_JOBS\n    --limit OUTPUT_CHARS\n    --count ATTACK_ROUNDS\natk exploit switch [OPTIONS] EXPLOIT_ID\natk exploit target [OPTIONS] COMMAND [ARGS]...\natk exploit target ls [OPTIONS] HISTORY_ID\natk exploit target off [OPTIONS] HISTORY_ID [TARGET_IPS]...\natk exploit target on [OPTIONS] HISTORY_ID [TARGET_IPS]...\n\natk flag ids [OPTIONS] [SERVICE]\n    --target TARGET\n    --no-target TARGET\n    --all-targets\n    --ignore-exclusions\natk flag submit [OPTIONS] [FLAGS]...\n\natk service ls [OPTIONS]\n```"
   }
  },
  {
   "title": "Flags per exploit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  concat(exploit_histories.service, ' (',left(exploits.docker_name, -17), ')'), COALESCE(COUNT(flags.id), 0) AS \" \" ,\n  date_bin(INTERVAL '$tick_time',executions.timestamp, TIMESTAMP '$ctf_start')\nFROM executions\n  LEFT JOIN flags on flags.execution_id = executions.id\n  INNER JOIN jobs on jobs.id = executions.job_id\n  INNER JOIN exploits on jobs.exploit_id = exploits.id\n  INNER JOIN exploit_histories on exploit_histories.id = exploits.exploit_history_id\nWHERE\n  flags.status = 'OK'\n  AND $__timeFilter(executions.timestamp)\nGROUP BY\n  concat(exploit_histories.service, ' (',left(exploits.docker_name, -17), ')'),\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start')\nORDER BY\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start');\n"
    }
   ]
  },
  {
   "title": "Flags last tick",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(flags.id)\nFROM\n  executions\n  LEFT JOIN flags ON flags.execution_id = executions.id\nWHERE\n  executions.timestamp BETWEEN date_bin(INTERVAL '$tick_time', (TIMESTAMP $__timeTo()) - INTERVAL '$tick_time', TIMESTAMP '$ctf_start') AND date_bin(INTERVAL '$tick_time', $__timeTo(), TIMESTAMP '$ctf_start')\n  AND flags.status = 'OK'\n"
    }
   ]
  },
  {
   "title": "Flags overall",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(flags.id)\nFROM\n  executions\n  JOIN flags ON executions.id = flags.execution_id\nWHERE\n  executions.timestamp >= (TIMESTAMP '$ctf_start')\n  AND flags.status = 'OK';"
    }
   ]
  },
  {
   "title": "Flag status per tick - $services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_bin(INTERVAL '$tick_time',executions.timestamp, TIMESTAMP '$ctf_start'),\n  COALESCE(flags.status::TEXT, '<Null>') as status,\n  COALESCE(COUNT(flags.id), 0) as flags\nFROM executions\n  LEFT JOIN flags ON flags.execution_id = executions.id\n  INNER JOIN jobs ON jobs.id = executions.job_id\n  INNER JOIN exploits ON jobs.exploit_id = exploits.id\n  INNER JOIN exploit_histories ON exploit_histories.id = exploits.exploit_history_id\nWHERE\n  exploit_histories.service in ($services)\n  AND $__timeFilter(executions.timestamp)\n  AND flags.status IN ( $show_status )\nGROUP BY\n  flags.status,\n  date_bin(INTERVAL '$tick_time',executions.timestamp, TIMESTAMP '$ctf_start')\nORDER BY\n  date_bin(INTERVAL '$tick_time',executions.timestamp, TIMESTAMP '$ctf_start')\n;"
    }
   ]
  },
  {
   "title": "Viewing Tick",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(EXTRACT(EPOCH FROM (TIMESTAMP $__timeTo() - TIMESTAMP '$ctf_start')) AS INTEGER) / CAST(EXTRACT(EPOCH FROM INTERVAL '$tick_time') AS INTEGER) as current_tick;"
    }
   ]
  },
  {
   "title": "Flag status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT flags.status, count(flags.status)\nFROM executions\nJOIN flags ON flags.execution_id = executions.id\nWHERE $__timeFilter(executions.timestamp) AND flags.status IN ( $show_status )\nGROUP BY flags.status\n;"
    }
   ]
  },
  {
   "title": "Exploits",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  exploit_histories.service AS \"Service\",\n  exploits.id AS \"Exploit\",\n  exploits.exploit_history_id AS \"Exploit History\",\n  active AS \"Active\",\n  author AS \"Author\",\n  exploits.timestamp AS \"Timestamp\"\nFROM\n  exploits\n  INNER JOIN exploit_histories ON exploit_histories.id = exploits.exploit_history_id\nORDER BY exploits.timestamp DESC;\n;\n"
    }
   ]
  },
  {
   "title": "Latest Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n--  jobs.id AS \"ID\",\n  exploits.id AS \"Exploit\",\n  jobs.timestamp AS \"Timestamp\",\n  jobs.status AS \"Status\",\n  count(flags.flag) AS \"OK Flags\"\nFROM\n  jobs\n  INNER JOIN exploits ON jobs.exploit_id = exploits.id\n  INNER JOIN executions ON executions.job_id = jobs.id\n  LEFT OUTER JOIN flags ON flags.execution_id = executions.id\nWHERE\n  $__timeFilter(jobs.timestamp)\n  AND flags.status = 'OK'\nGROUP BY\n  jobs.id, exploits.id\nORDER BY\n  jobs.timestamp DESC\nLIMIT 100\n"
    }
   ]
  },
  { "title": "Flags per Target and Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "OK Flags - total",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  targets.ip,\n  targets.service,\n  COUNT(exec_flag.id) as ok_flag_count\nFROM\n  targets\n  LEFT OUTER JOIN (\n    SELECT\n      executions.target_id,\n      flags.id\n    FROM\n      executions\n      INNER JOIN flags on flags.execution_id = executions.id\n    WHERE\n      flags.status = 'OK'\n      AND $__timeFilter(executions.timestamp)\n  ) AS exec_flag ON exec_flag.target_id = targets.id\nGROUP BY\n  targets.ip,\n  targets.service\n  ORDER BY inet(targets.ip)\n;"
    }
   ]
  },
  {
   "title": "OK Flags - last tick",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  targets.ip,\n  targets.service,\n  COALESCE(COUNT(flag_exec.id), 0) as ok_flag_count\nFROM\n  targets\n  LEFT OUTER JOIN (\n    SELECT executions.*, flags.status as \"flag_status\"\n    FROM\n      executions\n      JOIN flags ON flags.execution_id = executions.id\n    WHERE\n      flags.status = 'OK'\n      AND executions.timestamp BETWEEN\n        date_bin(INTERVAL '$tick_time', (TIMESTAMP $__timeTo()) - INTERVAL '$tick_time', TIMESTAMP '$ctf_start')\n        AND date_bin(INTERVAL '$tick_time', $__timeTo(), TIMESTAMP '$ctf_start')\n  ) AS \"flag_exec\" ON flag_exec.target_id = targets.id\nGROUP BY\n  targets.ip,\n  targets.service\n  ORDER BY inet(targets.ip)\n;"
    }
   ]
  },
  { "title": "$services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }, "repeat": "services" },
  {
   "title": "Flag status per tick - $services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_bin(INTERVAL '$tick_time',executions.timestamp, TIMESTAMP '$ctf_start'),\n  COALESCE(flags.status::TEXT, '<Null>') as status,\n  COALESCE(COUNT(flags.id), 0) as flags\nFROM\n  executions\n  LEFT JOIN flags ON flags.execution_id = executions.id\n  INNER JOIN jobs ON jobs.id = executions.job_id\n  INNER JOIN exploits ON jobs.exploit_id = exploits.id\n  INNER JOIN exploit_histories ON exploit_histories.id = exploits.exploit_history_id\nWHERE\n  exploit_histories.service in ($services)\n  AND $__timeFilter(executions.timestamp)\n  AND flags.status IN ( $show_status )\nGROUP BY\n  flags.status,\n  date_bin(INTERVAL '$tick_time',executions.timestamp, TIMESTAMP '$ctf_start')\nORDER BY\n  date_bin(INTERVAL '$tick_time',executions.timestamp, TIMESTAMP '$ctf_start')\n"
    }
   ]
  },
  {
   "title": "OK Flags last tick - $services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(flags.id), exploit_histories.service\nFROM\n  executions\n  INNER JOIN jobs ON jobs.id = executions.job_id\n  INNER JOIN exploits ON jobs.exploit_id = exploits.id\n  INNER JOIN exploit_histories ON exploit_histories.id = exploits.exploit_history_id\n  LEFT JOIN flags ON flags.execution_id = executions.id\nWHERE\n  exploit_histories.service IN ( $services )\n  AND executions.timestamp BETWEEN\n    date_bin(INTERVAL '$tick_time', (TIMESTAMP $__timeTo()) - INTERVAL '$tick_time', TIMESTAMP '$ctf_start')\n    AND date_bin(INTERVAL '$tick_time', $__timeTo(), TIMESTAMP '$ctf_start')\n  AND flags.status = 'OK'\nGROUP BY\n  exploit_histories.service\n"
    }
   ]
  },
  {
   "title": "Flag status - $services",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  flags.status,\n  count(flags.id)\nFROM\n  executions\n  INNER JOIN targets ON targets.id = executions.target_id\n  INNER JOIN flags ON flags.execution_id = executions.id\nWHERE\n  $__timeFilter(executions.timestamp)\n  AND targets.service = $services\n  AND flags.status IN ( $show_status )\nGROUP BY\n  flags.status\n;"
    }
   ]
  },
  {
   "title": "Exploitable Targets",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT targets.ip) AS \"All\"\nFROM\n  targets\nWHERE\n  targets.service IN ( $services )\n  AND targets.timestamp BETWEEN\n    date_bin(INTERVAL '$tick_time', (TIMESTAMP $__timeTo()) - INTERVAL '$tick_time', TIMESTAMP '$ctf_start')\n    AND date_bin(INTERVAL '$tick_time', $__timeTo(), TIMESTAMP '$ctf_start')\n;"
    },
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT targets.ip) as \"Exploitable\"\nFROM\n  targets\n  JOIN executions ON executions.target_id = targets.id\n  JOIN jobs ON jobs.id = executions.job_id\n  JOIN exploits ON exploits.id = jobs.exploit_id\n  JOIN exploit_histories ON exploit_histories.id = exploits.exploit_history_id\n  LEFT OUTER JOIN exclusions ON exclusions.target_ip = targets.ip AND exclusions.exploit_history_id = exploit_histories.id\n  LEFT OUTER JOIN flags ON flags.execution_id = executions.id\nWHERE\n  targets.service in ( $services )\n  AND exclusions.target_ip IS NULL\n  AND flags.status = 'OK'\n  AND targets.timestamp BETWEEN\n    date_bin(INTERVAL '$tick_time', (TIMESTAMP $__timeTo()) - INTERVAL '$tick_time', TIMESTAMP '$ctf_start')\n    AND date_bin(INTERVAL '$tick_time', $__timeTo(), TIMESTAMP '$ctf_start')\n"
    }
   ]
  },
  {
   "title": "OK Flags per exploit - $services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT\n  left(exploits.docker_name, -17) as exploit,\n  COALESCE(COUNT(flags.id), 0) as flags_ok,\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start') as time\nFROM\n  executions\n  LEFT JOIN flags on flags.execution_id = executions.id\n  INNER JOIN jobs on jobs.id = executions.job_id\n  INNER JOIN exploits on jobs.exploit_id = exploits.id\n  INNER JOIN exploit_histories on exploit_histories.id = exploits.exploit_history_id\nWHERE\n  flags.status = 'OK'\n  AND exploit_histories.service in ($services)\n  AND $__timeFilter(executions.timestamp)\nGROUP BY\n  exploit_histories.service,\n  left(exploits.docker_name, -17),\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start')\nORDER BY\n  date_bin(INTERVAL '$tick_time', executions.timestamp, TIMESTAMP '$ctf_start')\n"
    }
   ]
  },
  {
   "title": "Flags overall",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT flags.id)\nFROM\n  executions\n  JOIN flags ON executions.id = flags.execution_id\n  JOIN targets ON targets.id = executions.target_id\nWHERE\n  executions.timestamp >= (TIMESTAMP '$ctf_start')\n  AND flags.status = 'OK'\n  AND targets.service IN ( $services )\n;\n"
    }
   ]
  }
 ]
}